name: lightmat2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - astropy
  - matplotlib
  - sympy
  - pandas
  - tqdm
  - scipy<1.13
  - sparse
  - ipywidgets
  - ipykernel